name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup repo
      run: |
        make setup_repo
    - name: Update Python tools
      run: |
        .venv/bin/activate && python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        .venv/bin/activate && make setup_install
    - name: Lint with flake8
      run: |
        .venv/bin/activate && make flake8
    - name: Test
      run: |
        .venv/bin/activate && make verify_commit
